### ISSUE TITLE
Update cosmiconfig dependency to `^7.0.0` to support `.cjs` extension

### ISSUE THREAD

**Issue by gbcreation** [JsonMa/validate-branch-name#2]
Could you please update the `cosmiconfig` dependency to at least version `^7.0.0` to support `.cjs` extension please ? Thank you.

**Comment by JsonMa** [comment]
> Could you please update the `cosmiconfig` dependency to at least version `^7.0.0` to support `.cjs` extension please ? Thank you.

Already support! If you like it, please star this project!

**Comment by gbcreation** [comment]
Nice! Thank you very much.
