### ISSUE TITLE
Unable to use \d

### ISSUE THREAD

**Issue by standbyoneself** [JsonMa/validate-branch-name#6]
Steps to reproduce:

`.validate-branch-namerc.js`
```js
module.exports = {
    // prettier-ignore
    pattern: '^(?:develop|(?:feat|fix)\/RMC-\d+|release\/(?:\d+.?)+[^.])$',
    errorMsg: 'Branch name is not valid!',
};
```

`git checkout -b feat/RMC-2363`

`npx validate-branch-name`

Output:
```
Result: "failed" 
Error Msg: Branch name is not valid! 
Branch Name: "feat/RMC-2363" 
Pattern:"/^(?:develop|(?:feat|fix)\/RMC-d+|release\/(?:d+.?)+[^.])$/g"
```

Why did it replace`\d` with `d` and why should I use `[0-9]` over `\d`?

**Comment by JsonMa** [comment]
> Steps to reproduce:
> 
> `.validate-branch-namerc.js`
> 
> ```js
> module.exports = {
>     // prettier-ignore
>     pattern: '^(?:develop|(?:feat|fix)\/RMC-\d+|release\/(?:\d+.?)+[^.])$',
>     errorMsg: 'Branch name is not valid!',
> };
> ```
> 
> `git checkout -b feat/RMC-2363`
> 
> `npx validate-branch-name`
> 
> Output:
> 
> ```
> Result: "failed" 
> Error Msg: Branch name is not valid! 
> Branch Name: "feat/RMC-2363" 
> Pattern:"/^(?:develop|(?:feat|fix)\/RMC-d+|release\/(?:d+.?)+[^.])$/g"
> ```
> 
> Why did it replace`\d` with `d` and why should I use `[0-9]` over `\d`?

- Using '^(?:develop|(?:feat|fix)\/RMC-\\d+|release\/(?:\\d+.?)+[^.])$' or /^(?:develop|(?:feat|fix)\/RMC-\d+|release\/(?:\d+.?)+[^.])$/g directly. 
- Remind that there is a double \\ like this <img width="224" alt="image" src="https://user-images.githubusercontent.com/13042493/165307304-7d0c8abb-c734-472c-af8f-d53689c3c60b.png">

**Comment by standbyoneself** [comment]
Solved by using double slash, thanks

**Comment by JsonMa** [comment]
> Solved by using double slash, thanks

If this really helps you, please give this project a star.

**Comment by standbyoneself** [comment]
Done!
