### ISSUE TITLE
Error: not a git repository

### ISSUE THREAD

**Issue by ellierider** [JsonMa/validate-branch-name#7]
When I run `npx validate-branch-name` it says "Error: not a git repository"

Here is my test case:

```
mkdir test
cd test
git init
npm i validate-branch-name -D
npx validate-branch-name
```

I am running this on macOS Ventura. Same output on both Intel and M platforms.

**Comment by JsonMa** [comment]
> When I run `npx validate-branch-name` it says "Error: not a git repository"
> 
> Here is my test case:
> 
> ```
> mkdir test
> cd test
> git init
> npm i validate-branch-name -D
> npx validate-branch-name
> ```
> 
> I am running this on macOS Ventura. Same output on both Intel and M platforms.

git commit your project and try it again.

**Comment by ellierider** [comment]
That worked! Thank you
